-- Event
insert into Event select 'Blue Twilight Week Zero', 'Eagan, MN', 'btwz', getdate() where not exists (select 1 from Event where name = 'Blue Twilight Week Zero');

-- Game Event
insert into GameEvent select e.Id, g.Id, '02/17/2024', getdate(), null from event e, game g where e.Name = 'Blue Twilight Week Zero' and g.name = 'Crescendo' and not exists (select 1 from GameEvent ge where ge.eventId = e.id and ge.gameId = g.id);

-- Teams
insert into Team select 2220, 'Blue Twilight', 'Eagan, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 2220);
insert into Team select 6217, 'Bomb-Botz', 'Cannon Falls, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 6217);
/*
insert into Team select 1816, 'The Green Machine', 'Edina, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 1816);
insert into Team select 2052, 'Blue Twilight', 'New Brighton, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 2052);
insert into Team select 2181, 'GEARs', 'Blaine, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 2181);
insert into Team select 2225, 'Rebel Robotics', 'Champlin Park, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 2225);
insert into Team select 2239, 'Technocrats', 'Hopkins, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 2239);
insert into Team select 2472, 'Centurions', 'Circle Pines, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 2472);
insert into Team select 2491, 'NoMythic', 'St. Paul, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 2491);
insert into Team select 2498, 'BearBotics', 'Minneapolis, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 2498);
insert into Team select 2502, 'Talon Robotics', 'Eden Prairie, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 2502);
insert into Team select 2549, 'Millerbots', 'Minneapolis, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 2549);
insert into Team select 2846, 'Firebears', 'Roseville, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 2846);
insert into Team select 3007, 'RoboTitans', 'Oakdale, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 3007);
insert into Team select 3058, 'Anndroids', 'Annandale, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 3058);
insert into Team select 3082, 'Chicken Bot Pie', 'Minnetonka, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 3082);
insert into Team select 3206, 'Royal T-Wrecks', 'Woodbury, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 3206);
insert into Team select 3291, 'Au Pirates', 'Brooklyn Park, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 3291);
insert into Team select 3407, 'Wild Cards', 'Arden Hills, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 3407);
insert into Team select 3454, 'Mahtomedi Z-Bots', 'Mahtomedi, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 3454);
insert into Team select 3630, 'Stampede', 'Golden Valley, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 3630);
insert into Team select 3740, 'Storm Robotics', 'Sauk Rapids, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 3740);
insert into Team select 4198, 'Waconia RoboCats', 'Waconia, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 4198);
insert into Team select 4511, 'Power Amplified', 'Plymouth, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 4511);
insert into Team select 4607, 'Becker Robotics', 'Becker, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 4607);
insert into Team select 4728, 'ROCORI Robotics', 'Cold Spring, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 4728);
insert into Team select 4859, 'The Cybears', 'Byron, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 4859);
insert into Team select 6045, 'Sabre Robotics', 'Sartell, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 6045);
insert into Team select 7038, 'Pizza Pi''s', 'Fridley, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 7038);
insert into Team select 7258, 'Robolobos', 'Minneapolis, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 7258);
insert into Team select 7797, 'RipSaw Robotics', 'Cloquet, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 7797);
insert into Team select 8234, 'Panthinators', 'Spring Lake Park, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 8234);
insert into Team select 8516, 'Wired Up', 'Andover, MN', getdate(), null where not exists (select 1 from Team where teamNumber = 8516);
*/

-- Team Game Events
insert into TeamGameEvent (teamId, gameEventId, lastUpdated) select t.id, ge.id, getdate() from team t, gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and t.teamNumber = 2220 and not exists (select 1 from TeamGameEvent tge where tge.teamId = t.id and tge.gameEventId = ge.id);
insert into TeamGameEvent (teamId, gameEventId, lastUpdated) select t.id, ge.id, getdate() from team t, gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and t.teamNumber = 6217 and not exists (select 1 from TeamGameEvent tge where tge.teamId = t.id and tge.gameEventId = ge.id);

-- Matches
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '01', '02/17/2024 09:00:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 09:00:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '02', '02/17/2024 09:10:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 09:10:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '03', '02/17/2024 09:20:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 09:20:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '04', '02/17/2024 09:30:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 09:30:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '05', '02/17/2024 09:40:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 09:40:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '06', '02/17/2024 09:50:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 09:50:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '07', '02/17/2024 10:00:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 10:00:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '08', '02/17/2024 10:10:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 10:10:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '09', '02/17/2024 10:20:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 10:20:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '10', '02/17/2024 10:30:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 10:30:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '11', '02/17/2024 10:40:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 10:40:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '12', '02/17/2024 10:50:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 10:50:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '13', '02/17/2024 11:00:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 11:00:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '14', '02/17/2024 11:10:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 11:10:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '15', '02/17/2024 11:20:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 11:20:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '16', '02/17/2024 11:30:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 11:30:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '17', '02/17/2024 11:40:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 11:40:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '18', '02/17/2024 11:50:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 11:50:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '19', '02/17/2024 12:00:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 12:00:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '20', '02/17/2024 12:10:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 12:10:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '21', '02/17/2024 12:20:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 12:20:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '22', '02/17/2024 12:30:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 12:30:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '23', '02/17/2024 12:40:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 12:40:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '24', '02/17/2024 12:50:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 12:50:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '25', '02/17/2024 13:00:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 13:00:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '26', '02/17/2024 13:10:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 13:10:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '27', '02/17/2024 13:20:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 13:20:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '28', '02/17/2024 13:30:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 13:30:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '29', '02/17/2024 13:40:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 13:40:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '30', '02/17/2024 13:50:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 13:50:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '31', '02/17/2024 14:00:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 14:00:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '32', '02/17/2024 14:10:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 14:10:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '33', '02/17/2024 14:20:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 14:20:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '34', '02/17/2024 14:30:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 14:30:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '35', '02/17/2024 14:40:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 14:40:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '36', '02/17/2024 14:50:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 14:50:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '37', '02/17/2024 15:00:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 15:00:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '38', '02/17/2024 15:10:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 15:10:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '39', '02/17/2024 15:20:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 15:20:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '40', '02/17/2024 15:30:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 15:30:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '41', '02/17/2024 15:40:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 15:40:00');
insert into Match (gameEventId, number, dateTime, type, isActive, lastUpdated) select ge.Id, '42', '02/17/2024 15:50:00', 'PR', 'Y', getdate() from gameEvent ge inner join game g on g.id = ge.gameId inner join event e on e.id = ge.eventId where g.name = 'Crescendo' and e.name = 'Blue Twilight Week Zero' and not exists (select 1 from match m where m.gameEventId = ge.id and m.dateTime = '02/17/2024 15:50:00');

